apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.2.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        grafana:
          grafana.ini:
            feature_toggles:
              transformationsVariableSupport: true
          service:
            type: LoadBalancer
          persistence:
            enabled: true
            storageClassName: synology-grafana
            accessModes:
              - ReadWriteMany
            size: 10Gi

          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule

        prometheus:
          service:           # Move service to this level
            type: LoadBalancer
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-prometheus
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 80Gi
            additionalScrapeConfigs:
              - job_name: 'proxmox-nodes'
                static_configs:
                  - targets:
                      - '192.168.20.11:9100'
                      - '192.168.20.12:9100'
                      - '192.168.20.13:9100'
                      - '192.168.20.14:9100'
                metrics_path: /metrics
                scheme: http
                scrape_interval: 30s

        alertmanager:
          service:           # Move service to this level
            type: LoadBalancer
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-alertmanager
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 10Gi

        prometheusOperator:
          admissionWebhooks:
            enabled: true
          tlsProxy:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
