alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: synology-nfs
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 10Gi
          volumeName: synology-nfs-pv
          volumeMounts:
            - mountPath: /alertmanager
              subPath: alert-manager
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload-type/monitoring
                  operator: In
                  values:
                    - "true"
