prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: synology-nfs
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 80Gi
          volumeName: synology-nfs-pv
          volumeMounts:
            - mountPath: /prometheus
              subPath: prometheus
    retention: 30d
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload-type/monitoring
                  operator: In
                  values:
                    - "true"
